# Generated by Django 4.1.7 on 2023-04-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('signupdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
