# Generated by Django 4.1.7 on 2023-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0003_reg_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_form_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('occupation', models.CharField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),

        migrations.DeleteModel(name='Reg_Student'),
        migrations.DeleteModel(name='User_form_model'),
    ]
