# Generated by Django 4.1.7 on 2023-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0004_user_form_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('stdClass', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_form_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('occupation', models.CharField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
